### ISSUE TITLE
Feature Request: Search feature within the website

### ISSUE THREAD

**Issue by cccsss01** [spiffe/spiffe.io#282] opened 2023-07-12 18:30 UTC
It would be beneficial if there was a search feature enabled for the website.

**Comment by sanderson042** [comment] 2023-08-28 20:20
I agree, though I think this issue is a duplicate of the earlier issue #183.

**Comment by mchurichi** [comment] 2024-04-03 13:43
> It would be beneficial if there was a search feature enabled for the website.
Agreed!

Closing as duplicate of #183.

**Closed by mchurichi** 2024-04-03 13:43 UTC
